### ISSUE TITLE
Explain how to use this.

### ISSUE THREAD

**Issue by iGPLTV** [echojc/osu-ds#2]
I think I need a ODS file, you have a template for one?

**Comment by peppy** [comment]
There used to be a hidden key on osu-stable to do this export. That said, the format shouldn't be hard to figure out yourself.

We can't provide official support here, sorry.

**Comment by iGPLTV** [comment]
I am sorry to reopen this, but osu-stable isn't a repo so I am not sure what you mean :/

**Comment by iGPLTV** [comment]
Sorry for being so immature here. Apologies.

**Comment by peppy** [comment]
you're fine!
