### ISSUE TITLE
Another question... (please read)

### ISSUE THREAD

**Issue by iGPLTV** [echojc/osu-ds#3]
So, I read this and found your explanation of a "hidden key" on osu-stable very inconclusive. How am I supposed to find this? I don't have the code of osu-stable, and I don't even know what you mean by "hidden key" and if it is "hidden" how am I supposed to find it easily? (peppy marked my last one as solved without explaining himself fully)

**Comment by peppy** [comment]
You're not supposed to find it. Figure out the format yourself and make a converter.
